packages:
  - packages/**

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

catalog:
  '@intlify/eslint-plugin-vue-i18n': ^4.4.0
  '@libsql/client': ^0.17.3
  '@nuxt/content': ^3.13.0
  '@nuxt/eslint': ^1.15.2
  '@nuxt/eslint-config': ^1.15.2
  '@nuxt/fonts': ^0.14.0
  '@nuxt/hints': ^1.1.1
  '@nuxt/icon': ^2.2.2
  '@nuxt/image': ^2.0.0
  '@nuxt/scripts': ^0.13.2
  '@nuxt/test-utils': ^4.0.3
  '@nuxt/ui': ^4.7.1
  '@nuxtjs/i18n': ^10.3.0
  '@nuxtjs/robots': ^6.0.8
  '@pinia/nuxt': ^0.11.3
  '@tailwindcss/forms': ^0.5.11
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.3.0
  '@unhead/vue': ^3.0.3
  '@vitest/coverage-v8': ^4.1.6
  '@vitest/eslint-plugin': ^1.6.17
  '@vue/test-utils': ^2.4.10
  '@vueuse/core': ^14.2.1
  '@vueuse/nuxt': ^14.3.0
  consola: ^3.4.2
  eslint: ^10.3.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-oxlint: ^1.64.0
  happy-dom: ^20.9.0
  nuxt: ^4.4.5
  nuxt-auth-utils: ^0.5.29
  nuxt-security: ^2.6.0
  oxfmt: ^0.49.0
  oxlint: ^1.64.0
  pinia: ^3.0.4
  playwright-core: ^1.60.0
  prettier: ^3.8.3
  prettier-plugin-tailwindcss: ^0.8.0
  stylelint: ^17.11.1
  stylelint-config-standard: ^40.0.0
  stylelint-config-standard-vue: ^1.0.0
  tailwindcss: ^4.3.0
  typescript: ^6.0.2
  vitest: ^4.1.6
  vue: ^3.6.0-beta.10
  vue-router: ^5.0.7
  vue-tsc: ^3.2.9
  zod: ^4.3.6

cleanupUnusedCatalogs: true

minimumReleaseAge: 60

overrides:
  vite: ^8.0.8

strictDepBuilds: true

verifyDepsBeforeRun: install
