packages:
  - packages/**

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true

catalog:
  '@intlify/eslint-plugin-vue-i18n': ^4.1.1
  '@libsql/client': ^0.15.15
  '@nuxt/content': ^3.10.0
  '@nuxt/eslint': ^1.12.1
  '@nuxt/eslint-config': ^1.12.1
  '@nuxt/fonts': ^0.12.1
  '@nuxt/hints': 1.0.0-alpha.5
  '@nuxt/icon': ^2.2.0
  '@nuxt/image': ^2.0.0
  '@nuxt/scripts': ^0.13.2
  '@nuxt/test-utils': ^3.23.0
  '@nuxt/ui': ^4.3.0
  '@nuxtjs/i18n': ^10.2.1
  '@nuxtjs/robots': ^5.6.7
  '@pinia/nuxt': ^0.11.3
  '@tailwindcss/forms': ^0.5.11
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.1.18
  '@unhead/vue': ^2.1.2
  '@vitest/eslint-plugin': ^1.6.6
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^14.1.0
  '@vueuse/nuxt': ^14.1.0
  consola: ^3.4.2
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-oxlint: ^1.39.0
  happy-dom: ^20.3.0
  nuxt: ^4.2.2
  nuxt-auth-utils: ^0.5.27
  nuxt-security: ^2.5.0
  oxlint: ^1.39.0
  pinia: ^3.0.4
  playwright-core: ^1.57.0
  prettier: ^3.8.0
  prettier-plugin-tailwindcss: ^0.7.2
  stylelint: ^16.26.1
  stylelint-config-standard: ^39.0.1
  stylelint-config-standard-vue: ^1.0.0
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  vitest: ^4.0.17
  vue: 3.6.0-beta.3
  vue-router: ^4.6.4
  vue-tsc: ^3.2.2
  zod: ^4.3.5

cleanupUnusedCatalogs: true

minimumReleaseAge: 360

overrides:
  vite: ^8.0.0-beta.8

strictDepBuilds: true

verifyDepsBeforeRun: install
