name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: ${{ github.event_name != 'push' }}
#   group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
#   cancel-in-progress: true

jobs:
  CI:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v6

      - name: 🚧 Setup pnpm
        uses: pnpm/action-setup@v6

      - name: 🛠️ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 📝 Lint
        run: pnpm lint

      - name: 🧫 Type check
        run: pnpm typecheck

      - name: 🧪 Test project
        run: pnpm test
